config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  get 'homes/index' ,to: 'homes#index'
  get 'users/profile_edit' ,to: 'users#profile_edit'
  patch 'users/profile_update' ,to: 'users#profile_update'
  get 'users/account' ,to: 'users#account'
  get 'users/profile' ,to: 'users#profile'
  get 'rooms/search' ,to: 'rooms#search'

  resources :rooms
  resources :homes, :only => :index 
  resources :reservations do
    member do
      post 'confirm' ,to: 'reservations#confirm'
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations'}
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms

  validates :name, presence: true
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_one_attached :image
         
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  #protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
  def account
    @user = current_user
  end

  def profile
    @user = current_user
  end

  def profile_edit
    @user = current_user
  end

  def profile_update
    @user = current_user
    if @user.update(user_params)
      redirect_to users_profile_path
    else
      render "users/profile_edit"
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :self_introduction, :image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<h2>ユーザー詳細</h2>

<table border="1" class="table">
     <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
    </tr>
    <tr>
        <th>パスワード</th>
        <td> ******** </td>
    </tr>
</table>
<%= link_to "編集", edit_user_registration_path %>

<div class="userAccountProfile">
    <p><%= link_to "アカウント", users_account_path %></p>
    <p><%= link_to "プロフィール", users_profile_path %></p>
</div>

 <%= link_to "戻る", :back %>

app/views/users/profile.html.erb
<h2>ユーザープロフィール</h2>


    <table border="1" class="table">
        <tr>
            <th>アイコン画像</th>
            <% if @user.image.blank? %>      
                <td><%= image_tag 'user_img.png', size: "50x50" %></td>  
            <% else %>
                <td><%= image_tag @user.image.variant(resize: "50x50") %></td>
            <% end %>
        </tr>
        <tr>
            <th>名前</th>
            <td><%= @user.name %></td>
        </tr>
        <tr>
            <th>自己紹介</th>
            <td><%= @user.self_introduction %></td>
        </tr>
    </table>
    <p><%= link_to "編集", users_profile_edit_path %></p>


<div class="userAccountProfile">
    <% if user_signed_in? && @user == current_user %>
        <p><%= link_to "アカウント", users_account_path %></p>
        <p><%= link_to "プロフィール", users_profile_path %></p>            
    <% end %>
</div>

<%= link_to "戻る", :back %>

app/views/users/profile_edit.html.erb
<h2>ユーザープロフィール編集</h2>

<%= form_with model: @user, url: users_profile_update_path, method: :patch do |f| %>
    <table border="1" class="table">
        <tr>
            <th><%= f.label :name, "名前" %></th>
            <td><%= f.text_field :name %></td>
        </tr>
        <tr>
            <th><%= f.label :self_introduction, "自己紹介" %></th>
            <td><%= f.text_field :self_introduction %></td>
        </tr>
        <tr>
            <th><%= f.label :image, "アイコン" %></th>
            <td><%= f.file_field :image %></td>
        </tr>
    </table>
    <%= f.submit "保存" %>

    <% if @user.errors.any? %>
    <div class="error_exclamation">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
    <% end %>
<% end %>

<%= link_to "戻る", users_profile_path %>

app/views/users/show.html.erb
<h2>ユーザー詳細</h2>

<p>メールアドレス</p><p><%= @user.email %></p>
<p>パスワード</p><p> ******** </p>

<p><%= link_to "アカウント", users_show_path %></p>

<div>
    <% if user_signed_in? && @user == current_user %>
        <p><%= link_to "編集", edit_user_registration_path %></p>
    <% end %>
</div>

<p>プロフィール</p>

<!-- <p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p> -->