config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  get 'homes/index' ,to: 'homes#index'
  get 'users/profile_edit' ,to: 'users#profile_edit'
  patch 'users/profile_update' ,to: 'users#profile_update'
  get 'users/account' ,to: 'users#account'
  get 'users/profile' ,to: 'users#profile'
  get 'rooms/search' ,to: 'rooms#search'

  resources :rooms
  resources :homes, :only => :index 
  resources :reservations do
    member do
      post 'confirm' ,to: 'reservations#confirm'
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations'}
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @user = current_user
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<h1 class="hotelReservationTitle">HotelReservation</h1>

<div class="searchForm">
    <p>エリアで検索</p>
    <%= search_form_for @q, url: rooms_search_path do |f| %>
        <% f.label :address_cont %>
        <%= f.search_field :address_cont, :placeholder => "エリア名を入力"  %>
        <%= f.submit %>
    <% end %>
</div>

<div class="searchForm">
    <p>フリーワードで検索</P>
    <%= search_form_for @q, url: rooms_search_path do |f| %>
        <% f.label :name_or_information_cont %>
        <%= f.search_field :name_or_information_cont, :placeholder => "キーワードを入力"  %>
        <%= f.submit %>
    <% end %>
</div>