config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  get 'homes/index' ,to: 'homes#index'
  get 'users/profile_edit' ,to: 'users#profile_edit'
  patch 'users/profile_update' ,to: 'users#profile_update'
  get 'users/account' ,to: 'users#account'
  get 'users/profile' ,to: 'users#profile'
  get 'rooms/search' ,to: 'rooms#search'

  resources :rooms
  resources :homes, :only => :index 
  resources :reservations do
    member do
      post 'confirm' ,to: 'reservations#confirm'
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations'}
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations
    has_one_attached :image
    validates :name, presence: true
    validates :information, presence: true
    validates :address, presence: true
    validates :price, presence: true
    
    def self.ransackable_attributes(auth_object = nil)
        ["address", "created_at", "id", "information", "name", "price", "updated_at", "user_id"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["image_attachment", "image_blob", "user"]
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @user = current_user
    @rooms = @user.rooms
  end

  def new
    @user = current_user
    @room = Room.new
  end

  def create
    @user = current_user
    @room = Room.new(params.require(:room).permit(:name, :information, :price, :address, :user_id, :image))
    if @room.save
      redirect_to rooms_path
    else
      render "new"
    end
  end

  def show
    @user = current_user
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end

  def edit
    @user = current_user
    @room = Room.find(params[:id])
  end

  def update
    @user = current_user
    @room = Room.find(params[:id])
    if @room.update(params.require(:room).permit(:name, :information, :price, :address, :user_id, :image))
      redirect_to rooms_path
    else
      render "edit"
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  def search
    @user = current_user
    @q = Room.ransack(params[:q])
    @rooms = @q.result(distinct: true)
  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/edit.html.erb
<h2>施設情報編集</h2>

<%= form_with model: @room do |f| %>
  <table border="1" class="table">
    <tr>
      <th><%= f.label :name, "施設名 *" %></th>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th><%= f.label :information, "施設情報 *" %></th>
      <td><%= f.text_area :information %></td>
    </tr>
    <tr>
      <th><%= f.label :price, "料金/日 *" %></th>
      <td><%= f.number_field :price %></td>
    </tr>
    <tr>
      <th><%= f.label :address, "住所 *" %></th>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <th><%= f.label :image, "画像" %></th>
      <td><%= f.file_field :image %></td>
    </tr>
  </table>
  <%= f.hidden_field :user_id, value: @user.id %>
  <p>◆ *は必須項目です。</p>
  <p>◆ 料金は半角数字で入力して下さい。</p>
  <%= f.submit "編集を完了する" %>

  <% if @room.errors.any? %>
  <div class="error_exclamation">
    <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
<% end %>



<%= link_to "戻る", :back %>

app/views/rooms/index.html.erb
<h2>登録済施設一覧</h2>

<table border="1" class="table">
  <tr>
    <th>画像</th>
    <th>施設名</th>
    <th>施設情報</th>
    <th>宿泊料金（円/日）</th>
    <th>作成日</th>
  </tr> 
    <% @rooms.each do |room| %>
    <tr>
    <% if room.image.blank? %>
      <td><%= image_tag 'institution.png', size: "80x50" %></td>
    <% else %>
      <td><%= image_tag room.image.variant(resize: "50x50") %></td>
    <% end %>
    <td><%= link_to "#{room.name}", room %></td>
    <td><%= room.information %></td>
    <td><%= room.price %></td>
    <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <% end %>
</table>

<%= link_to "戻る", :back %>

app/views/rooms/new.html.erb
<h2>施設新規登録</h2>

<%= form_with model: @room do |f| %>
  <table border="1" class="table">
    <tr>
      <th><%= f.label :name, "施設名 *" %></th>
      <td><%= f.text_field :name %></td>
    </tr> 
    <tr>
      <th><%= f.label :information, "施設情報 *" %></th>
      <td><%= f.text_area :information %></td>
    </tr>
    <tr>
      <th><%= f.label :price, "料金/日 *" %></th>
      <td><%= f.number_field :price %></td>
    </tr>
    <tr>
      <th><%= f.label :address, "住所 *" %></th>
      <td><%= f.text_field :address %></td>
    </tr>
    <tr>
      <th><%= f.label :image, "画像" %></th>
      <td><%= f.file_field :image %></td>
    </tr>
  </table>
  <%= f.hidden_field :user_id, value: @user.id %>
  <p>◆ *は必須項目です。</p>
  <p>◆ 料金は半角数字で入力して下さい。</p>
  <%= f.submit "登録する" %>

  <% if @room.errors.any? %>
    <div class="error_exclamation">
      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

<%= link_to "戻る", :back %>

app/views/rooms/search.html.erb
<h2>検索結果</h2>

<% if @rooms.present? %>
  <table border="1" class="table">
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>住所</th>
      <th>施設詳細</th>
      <th>宿泊料金（/日）</th>
    </tr>
    <% @rooms.each do |room| %> 
      <tr>
        <% if room.image.blank? %>
          <td><%= image_tag 'institution.png', size: "80x50" %></td>
        <% else %>
          <td><%= image_tag room.image.variant(resize: "80x50") %></td>
        <% end %>
        <td><%= link_to "#{room.name}", room %></td>
        <td><%= room.address %></td>
        <td><%= room.information %></td>
        <td><%= room.price %></td>
      </tr>
    <% end %>
  </table>
  <p>検索結果</span><%= @rooms.count %><span>件</p>
<% else %>
  <p>検索結果はありません</p>
<% end %>

<%= link_to "戻る", :back %>

app/views/rooms/show.html.erb
<h2>施設詳細</h2>

<% if @room.image.blank? %>
  <p><%= image_tag 'institution.png', size: "400x200" %></p>
<% else %>
  <td><%= image_tag @room.image.variant(resize: "400x200") %></td>
<% end %>

<table border="1" class="table">
  <tr>
    <th>施設名</th>
    <td><%= @room.name %></td>
  </tr>
  <tr>
    <th>施設情報</th>
    <td><%= @room.information %></td>
  </tr>
  <tr>
    <th>料金（円/日）</th>
    <td><%= @room.price %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @room.address %></td>
  </tr>
</table>

<% if user_signed_in? %>
  <% if @user.id == @room.user.id %>
    <%= link_to "編集", edit_room_path %>
    <%= link_to "削除", "/rooms/#{@room.id}", method: :delete, data: {confirm:"本当に削除しますか"} %>
  <% else %>
  <% end %>

  <%= form_with model: @reservation, url:confirm_reservation_path do |f| %>
    <table border="1" class="table">
      <tr>
        <th><%= f.label :check_in, "チェックイン *" %></th>
        <td><%= f.date_field :check_in %></td>
      </tr>
      <tr>
        <th><%= f.label :check_out, "チェックアウト *" %></th>
        <td><%= f.date_field :check_out %></td>
      </tr>
      <tr>
        <th><%= f.label :number_of_people, "人数 *" %></th>
        <td><%= f.number_field :number_of_people, min: 1 %></td>
      </tr>
    </table>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <p>◆ *は必須項目です。</p>
    <p>◆ 人数は半角数字で入力して下さい。</p>
    <%= f.submit "予約する" %>
  <% end %>
<% end %>

<%= link_to "戻る", :back %>