config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#index'
  get 'homes/index' ,to: 'homes#index'
  get 'users/profile_edit' ,to: 'users#profile_edit'
  patch 'users/profile_update' ,to: 'users#profile_update'
  get 'users/account' ,to: 'users#account'
  get 'users/profile' ,to: 'users#profile'
  get 'rooms/search' ,to: 'rooms#search'

  resources :rooms
  resources :homes, :only => :index 
  resources :reservations do
    member do
      post 'confirm' ,to: 'reservations#confirm'
    end
  end
  devise_for :users, controllers: { registrations: 'users/registrations'}
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelReservation</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <header class="sticky-top">
    <div class="header">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark text-white">
        <ul class="mr-auto">
          <li><%= link_to 'HotelReservation', homes_path %></li>
        </ul>
        <% if user_signed_in? %>
          <div class="userIcon">
            <% if @user.image.blank? %>
              <p><%= image_tag 'user_img.png', size: "40x40" %></p>
            <% else %>
              <p><%= image_tag @user.image.variant(resize: "40x40") %></p>
            <% end %>
          </div>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >
              <%= @user.name %>
            </button>
            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton1">
              <li class="dropdown-item"><%= link_to "施設の新規登録", new_room_path %></li>
              <li class="dropdown-item"><%= link_to "予約済一覧", reservations_path %></li>
              <li class="dropdown-item"><%= link_to "登録済一覧", rooms_path %></li>
              <li class="dropdown-item"><%= link_to "アカウント設定", users_account_path %></li>
              <li class="dropdown-item"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </div>
        <% else %>
          <ul>  
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
          </ul>
        <% end %>
      </nav>
    </div>
  </header>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>